import Head from 'next/head'
import Image from 'next/image'
import Jumbotron from '../components/Jumbotron/Jumbotron.js'
import DefaultLayout from '../layouts/Default.js'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Malya First Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
      <Jumbotron/>
      </DefaultLayout>
        
      
    </div>
  )
}
