import { React, useState, useEffect } from "react";
import DefaultLayout from "../../layouts/Default";
import Card from "../../components/Card/Card";
import Head from 'next/head'

export default function Index() {
  const [cats, setCats] = useState([]);

  const fetchCats = async () => {
    const response = await fetch("/api/cats");
    const data = await response.json();
    setCats(data);

  };

  useEffect(() => {
    fetchCats();
  }, []);
  

  return (<>
      <Head>
        <title>Our Cats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <DefaultLayout>
      <div className="container mt-5">
        <div style={{ display: "flex", flexWrap: "wrap" }}>
          {cats.map((cats) => (
            <Card
              key={cats.id}
              name={cats.name}
              phone={cats.phone}
              id={cats.id}
              email={cats.email}
              image={cats.image}
            />
          ))}
        </div>
      </div>
    </DefaultLayout>
    </>
  );
}
